### ISSUE TITLE
不能推送api 到内网api 平台

### ISSUE THREAD

**Issue by markla2014** [eolinker/eoapi-extensions#10]
![图片](https://user-images.githubusercontent.com/11838376/203286471-3908ecde-ea1c-47cc-b457-66b592e11d07.png)

**Comment by scarqin** [comment]
@markla2014 推送到内网的 Eolink？你的 Token 和 projectID 是否正确？

**Comment by markla2014** [comment]
![图片](https://user-images.githubusercontent.com/11838376/203288401-81a55af7-2bc6-4578-951c-9f9fc124fc6f.png)
![图片](https://user-images.githubusercontent.com/11838376/203288457-1846c555-b708-4c94-8ec4-eacfb42d167b.png)
应该没问题，除了数据库哪里还能获取？

**Comment by scarqin** [comment]
@markla2014 
密钥在这里：https://help.eolinker.com/openapi/html/v2.html
项目 Hashkey
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/15225835/203325621-cd1a769d-d4a3-47c5-97e0-c698d721d916.png">

**Comment by markla2014** [comment]
是不是因为开源版本所以不支持
![图片](https://user-images.githubusercontent.com/11838376/203347986-bc14de6b-8261-408d-85a6-816af74bd42c.png)
![图片](https://user-images.githubusercontent.com/11838376/203348217-17a5e66c-dce7-4a2a-be4a-d803d7d2ec34.png)

**Comment by scarqin** [comment]
你的目的是分享 API 还是？不太理解。
推送到 Eolink 的功能是将 API 推送到另一个平台：https://www.eolink.com/

**Comment by markla2014** [comment]
是不是自行搭建的remote-server 不能被推送
![图片](https://user-images.githubusercontent.com/11838376/203463817-670a8fd3-f614-4c82-9248-6e17549d805f.png)

**Comment by scarqin** [comment]
@markla2014 加一下 Q 群：981965807 我详细了解下
