### ISSUE TITLE
ChatGPT机器人对话框字数限制问题

### ISSUE THREAD

**Issue by R-Tsubasa** [eolinker/eoapi-extensions#30]
![image](https://user-images.githubusercontent.com/75460222/226097356-58a218c1-8e1f-4a99-80b0-f1949353f584.png)

进行了一段时间的对话之后就会给出这个提示，感觉这个提示应该是对话框中总字数限制而不是单条消息的字数限制，不知道是故意设计成这样的还是bug。

**Comment by scarqin** [comment]
@R-Tsubasa 收到，因为有上下文，所以会把上下文传过去。
下个版本会优
