### ISSUE TITLE
ChatGPT机器人：使用次数提示问题

### ISSUE THREAD

**Issue by R-Tsubasa** [eolinker/eoapi-extensions#31]
![image](https://user-images.githubusercontent.com/75460222/227478206-624cfab7-cae2-497d-a68d-c0338a4545bc.png)
已经Star了项目，但每次使用一会儿之后还是会弹出这个提示，希望能优化一下，会一直支持此项目，祝越来越好~

**Comment by scarqin** [comment]
@R-Tsubasa 感谢反馈
