### ISSUE TITLE
APIPost导入只能导入文件夹，具体api无法导入

### ISSUE THREAD

**Issue by xingchen-c** [eolinker/eoapi-extensions#39]

**Comment by Changeeer** [comment]
请问一下能否提供F12浏览器的报错信息，或者一份脱敏数据给我们尝试复现

**Comment by scarqin** [comment]
@xingchen-c

**Comment by xingchen-c** [comment]
控制台的输出如下
![image](https://user-images.githubusercontent.com/22829505/231468988-5cda0191-75c8-43d3-9e66-42b0a0a40208.png)

**Comment by xingchen-c** [comment]
确实是超长了……已经成功导入，希望可以优化一下

**Comment by scarqin** [comment]
@Changeeer uri 长度调整到 500
