### ISSUE TITLE
如何查看当前epai项目安装的插件列表

### ISSUE THREAD

**Issue by FoSuCloud** [eolinker/eoapi-extensions#8]
安装了eapi之后，还需要额外安装eapi-extensions，执行pnpm changeset来查看插件列表吗？

**Comment by scarqin** [comment]
@FoSuCloud 插件列表界面就可以看，你是想要开发插件吗？
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/15225835/201530149-23b514e1-b155-4c2f-a86f-a079b5f5ba01.png">

**Comment by FoSuCloud** [comment]
那eapi-extensions是用于做什么的呢？我理解是用于管理插件的吧。

**Comment by scarqin** [comment]
官方插件的源代码仓库/示例仓库，如需开发插件，文档可见：https://developer.eoapi.io/

**Comment by FoSuCloud** [comment]
按照教程执行eo debug之后，.eo目录也出现对应项目了，但是已安装目录并没有对应插件显示
![image](https://user-images.githubusercontent.com/49218295/201530329-44b57ebb-d466-474c-9646-8d50a883e086.png)

**Comment by scarqin** [comment]
@FoSuCloud 重启下应用试试，你可以把你的 template 仓库上传下我看看。
方便说下想开发什么插件吗？
已经看你提了好几个关于插件系统的问题了，如果是想了解插件实现技术的话，感兴趣的话后续有文章可以推给你，可以加即时通讯群：https://docs.eoapi.io/docs/contact.html。

**Comment by FoSuCloud** [comment]
我的template其实就是直接eo g 生成的一个项目。目前是想了解插件实现技术。即时通讯群目前404Code: NOT_FOUND了

**Comment by scarqin** [comment]
@FoSuCloud https://docs.eoapi.io/docs/contact.html
嗯嗯你加微信吧。

**Comment by scarqin** [comment]
Issue 主要是用来交流产品使用上的问题，关于产品的 Bug 反馈/需求建议等等。
如果是想要研究架构/学习，目前还是得自己多看看源码，如果有不理解的我们微信交流。
